name: Build and Deploy
on:
    push:
        branches:
            - src
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install
              run: yarn

            - name: Build
              run: yarn run build
              env:
                  GAID: ${{ secrets.GAID }}
                  GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
                  GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
                  BAIDU_HMT_ID: ${{ secrets.BAIDU_HMT_ID }}

            - name: Deploy
              run: yarn run deploy
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
