name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@master
              env:
                  GAID: ${{ secrets.GAID }}
                  GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
                  GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: .vuepress/dist
                  BUILD_SCRIPT: npm install && npm run build
