name: Build and Deploy
on:
    push:
        branches:
            - src
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install
              run: npm install

            - name: Build and Deploy
              run: npm run-script deploy
              env:
                  GAID: ${{ secrets.GAID }}
                  GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
                  GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - name: Deploy
            #   uses: JamesIves/github-pages-deploy-action@release/v3
            #   with:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #       BRANCH: master
            #       FOLDER: .vuepress/dist
